# Lefthook configuration
# This file defines git hooks that automatically run
# No setup needed - just run 'bundle install' and hooks are active!

pre-commit:
  commands:
    rubocop:
      run: |
        set -e  # Exit on any error
        bundle exec rubocop -A --force-exclusion
        if [ -n "$(git diff --name-only)" ]; then
          git diff --name-only | xargs git add
        fi
      # This runs RuboCop with auto-fix on the entire project
      # and automatically stages ALL fixed files
